# Problem284
from turtle import *
a = Turtle()
a.penup()
a.goto(-100, 60)
a.pendown()
a.color("orange")
a.begin_fill()
for i in range(2):
    a.forward(200)
    a.right(90)
    a.forward(40)
    a.right(90)
a.end_fill()
a.penup()
a.goto(-100, 20)
a.pendown()
a.color("white")
a.begin_fill()
for i in range(2):
    a.forward(200)
    a.right(90)
    a.forward(40)
    a.right(90)
a.end_fill()
a.penup()
a.goto(-100, -20)
a.pendown()
a.color("green")
a.begin_fill()
for i in range(2):
    a.forward(200)
    a.right(90)
    a.forward(40)
    a.right(90)
a.end_fill()
a.penup()
a.goto(0, -20)
a.pendown()
a.color("blue")
a.circle(20)
a.penup()
a.goto(-100, 60)
a.pendown()
a.color("black")
a.right(90)
a.forward(400)
a.penup()
a.goto(-120, -340)
a.pendown()
a.color("black")
for i in range(2):
    a.forward(40)
    a.left(90)
    a.forward(50)
    a.left(90)
